DROP TABLE IF EXISTS timetable;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS lessons_info;


CREATE TABLE groups(
    id integer GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(10) UNIQUE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE students(
    id integer GENERATED ALWAYS AS IDENTITY,
    first_name VARCHAR(20) NOT NULL,
    last_name VARCHAR(20) NOT NULL,
    group_id int REFERENCES groups(id) ON DELETE RESTRICT,
    PRIMARY KEY (id)
);


CREATE TABLE subjects(
    id integer GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE lessons_info(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    start_time time NOT NULL,
    end_time time NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE timetable(
    id integer GENERATED ALWAYS AS IDENTITY,
    subject_id int REFERENCES subjects(id) ON DELETE CASCADE,
    class_date date NOT NULL,
    lesson_number smallint REFERENCES lessons_info(id) ON DELETE RESTRICT,
    class_room smallint NOT NULL,
    group_id int REFERENCES groups(id) ON DELETE CASCADE,
    PRIMARY KEY (id),
    UNIQUE (class_date, class_room, lesson_number)
);
